export const ADD_DATA_REGISTER = 'ADD_DATA_REGISTER';

export const REMOVE_DATA_REGISTER = 'REMOVE_DATA_REGISTER';

export const ADD_RESERVE_DATA = 'ADD_RESERVE_DATA';

export const REMOVE_RESERVE_DATA = 'REMOVE_RESERVE_DATA';

export default {
  ADD_DATA_REGISTER: 'ADD_DATA_REGISTER',
  REMOVE_DATA_REGISTER: 'REMOVE_DATA_REGISTER',
  SUPER_ROLE_USER: 3,
  ADMIN_ROLE_USER: 2
};
